# Generated by Django 5.0.6 on 2024-09-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_customuser_groups_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('parent', 'Parent'), ('employee', 'Employee')], default='parent', max_length=10),
        ),
    ]
